---
title: "Untitled"
output: html_document
---

```{r}

library(zipcodeR)
library(tidyverse)
library(igraph)
library(ggplot2)
library(geodist)

```

```{r}

ZIP <- read.table("C:/Users/86156/Desktop/Data Project/Zip/zcta_zcta_shard1.tsv", header=T, sep="\t")
ZC <- read.csv("C:/Users/86156/Desktop/Data Project/zip_code_database.csv")

```

```{r}

#PA zip code from 15001 to 19612
ZIP_PA <- ZIP %>% 
  filter(user_loc %in% 15001:19612 & fr_loc %in% 15001:19614) %>%
  distinct(scaled_sci,.keep_all = TRUE)

```

```{r}

#Calculate distance
ZIP_PA_DIS <- ZIP_PA %>% 
  mutate(zip_distance(user_loc, fr_loc)) %>%
  select(user_loc,fr_loc,scaled_sci,distance)

```

```{r}

#Plot sci vs. distance
ggplot(ZIP_PA_DIS,aes(distance,scaled_sci)) +
  geom_jitter(height = 2, width = 2)

```

```{r}

ZC1 <- plyr::rename(ZC, c('zip'='user_loc','county'='county_user'))
ZC2 <- plyr::rename(ZC, c('zip'='fr_loc','county'='county_fr'))

ZC1 <- ZC1 %>%
  select(user_loc,county_user)
  
ZC2 <- ZC2 %>%
  select(fr_loc,county_fr)

ZIP_PA_DIS <- merge(ZIP_PA_DIS,ZC1, by = 'user_loc')
ZIP_PA_DIS <- merge(ZIP_PA_DIS,ZC2, by = 'fr_loc')


```

```{r}


```





