---
title: "Untitled"
output: html_document
---

```{r}

library(zipcodeR)
library(tidyverse)
library(igraph)
library(ggplot2)
library(geodist)

```

```{r}

ZIP <- read.table("C:/Users/86156/Desktop/Data Project/Zip/zcta_zcta_shard1.tsv", header=T, sep="\t")
ZC <- read.csv("C:/Users/86156/Desktop/Data Project/zip_code_database.csv")

```

```{r}

#PA zip code from 15001 to 19612
ZIP_PA <- ZIP %>% 
  filter(user_loc %in% 15001:19612 & fr_loc %in% 15001:19614) %>%
  distinct(scaled_sci,.keep_all = TRUE)

```

```{r}

#Calculate distance
ZIP_PA_DIS <- ZIP_PA %>% 
  mutate(zip_distance(user_loc, fr_loc)) %>%
  select(user_loc,fr_loc,scaled_sci,distance)

```

```{r}

#Plot sci vs. distance
ggplot(ZIP_PA_DIS,aes(distance,scaled_sci)) +
  geom_jitter(height = 2, width = 2)

```

```{r}

ZC1 <- plyr::rename(ZC, c('zip'='user_loc','county'='county_user'))
ZC2 <- plyr::rename(ZC, c('zip'='fr_loc','county'='county_fr'))

ZC1 <- ZC1 %>%
  select(user_loc,county_user)
  
ZC2 <- ZC2 %>%
  select(fr_loc,county_fr)

ZIP_PA_DIS <- merge(ZIP_PA_DIS,ZC1, by = 'user_loc')
ZIP_PA_DIS <- merge(ZIP_PA_DIS,ZC2, by = 'fr_loc')


```

```{r}

u_r <- read.csv("C:/Users/86156/Desktop/Data Project/urban_rural.csv")

ZIP_PA_DIS <- merge(ZIP_PA_DIS,u_r, by.x = 'county_user', by.y = 'County')
ZIP_PA_DIS <- merge(ZIP_PA_DIS,u_r, by.x = 'county_fr', by.y = 'County')

ZIP_PA_DIS <- plyr::rename(ZIP_PA_DIS, c('U_R.x'='ur_user','U_R.y'='ur_fr'))

```

```{r}

ZIP_PA_DIS$ur_user[ZIP_PA_DIS$ur_user=="Rural"] = -1
ZIP_PA_DIS$ur_user[ZIP_PA_DIS$ur_user=="Urban"] = 1
ZIP_PA_DIS$ur_fr[ZIP_PA_DIS$ur_fr=="Rural"] = -1
ZIP_PA_DIS$ur_fr[ZIP_PA_DIS$ur_fr=="Urban"] = 1

ZIP_PA_DIS$ur_user <- as.numeric(ZIP_PA_DIS$ur_user)
ZIP_PA_DIS$ur_fr <- as.numeric(ZIP_PA_DIS$ur_fr)

ZIP_PA_DIS <- ZIP_PA_DIS %>%
  mutate('corelation' = ur_user*ur_fr)

ZIP_PA_DIS$corelation <- as.factor(ZIP_PA_DIS$corelation)

```

```{r}

ggplot(ZIP_PA_DIS, aes(x=corelation , y = log(scaled_sci))) +
  geom_boxplot()

t.test(ZIP_PA_DIS$scaled_sci ~ ZIP_PA_DIS$corelation)

```

```{r}



```




